import express from 'express';
import helmet from 'helmet';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
import { createHash, randomBytes } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createFieldCrypto, loadClinicalKey, safeErrorFingerprint } from './crypto.js';
import { createBackupRouter } from './backup.js';

const { Pool, Client } = pg;
const DATA_DIR=process.env.BETIPUL_DATA_DIR||'/data';
const OPTIONS_FILE=process.env.BETIPUL_OPTIONS_FILE||'/data/options.json';
const MIGRATIONS_DIR=new URL('../migrations/',import.meta.url);
const PORT=Number(process.env.PORT||3000);
const APP_VERSION=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8')).version;
const ROLES=['admin','therapist','office','finance','supervisor','viewer'];

async function readOptions(){try{return JSON.parse(await readFile(OPTIONS_FILE,'utf8'));}catch{return {admin_username:process.env.BETIPUL_ADMIN_USERNAME||'admin',admin_password:process.env.BETIPUL_ADMIN_PASSWORD||'change-me-now',backup_passphrase:process.env.BETIPUL_BACKUP_PASSPHRASE||''};}}
function dbConfig(database=process.env.PGDATABASE||'betipul'){return {host:process.env.PGHOST||'/run/postgresql',user:process.env.PGUSER||'postgres',database,max:12};}
async function ensureDatabase(){const client=new Client(dbConfig('postgres'));await client.connect();const found=await client.query("SELECT 1 FROM pg_database WHERE datname='betipul'");if(!found.rowCount)await client.query('CREATE DATABASE betipul');await client.end();}
await ensureDatabase();
const pool=new Pool(dbConfig());
await pool.query('CREATE TABLE IF NOT EXISTS schema_migrations(name TEXT PRIMARY KEY,applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW())');
for(const name of (await readdir(MIGRATIONS_DIR)).filter(n=>n.endsWith('.sql')).sort()){const found=await pool.query('SELECT 1 FROM schema_migrations WHERE name=$1',[name]);if(found.rowCount)continue;const client=await pool.connect();try{await client.query('BEGIN');await client.query(await readFile(new URL(name,MIGRATIONS_DIR),'utf8'));await client.query('INSERT INTO schema_migrations(name) VALUES($1)',[name]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}

const options=await readOptions();
const adminUsername=String(options.admin_username||'admin').trim();
const adminPassword=String(options.admin_password||'change-me-now');
const standaloneLoginReady=adminPassword!=='change-me-now'&&adminPassword.length>=12;
await pool.query("INSERT INTO users(username,display_name,password_hash,role) VALUES($1,$2,$3,'admin') ON CONFLICT(username) DO UPDATE SET password_hash=EXCLUDED.password_hash,updated_at=NOW()",[adminUsername,adminUsername,await bcrypt.hash(adminPassword,12)]);

await mkdir(path.join(DATA_DIR,'keys'),{recursive:true});
const fields=createFieldCrypto(await loadClinicalKey(DATA_DIR));
const jwtFile=path.join(DATA_DIR,'keys','session.key');let jwtSecret;try{jwtSecret=(await readFile(jwtFile,'utf8')).trim();}catch{jwtSecret=randomBytes(48).toString('base64url');await writeFile(jwtFile,jwtSecret,{mode:0o600});}

const app=express();app.disable('x-powered-by');app.set('trust proxy','loopback');
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'","data:"],connectSrc:["'self'"]}},referrerPolicy:{policy:'no-referrer'}}));
app.use(express.json({limit:'2mb'}));
const asyncRoute=(handler)=>(req,res,next)=>Promise.resolve(handler(req,res,next)).catch(next);
function cookieValue(req,name){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>{const[k,...v]=x.trim().split('=');return[k,decodeURIComponent(v.join('='))];}).filter(([k])=>k))[name];}
function publicUser(row){return {id:row.id,username:row.username,displayName:row.display_name,role:row.role,active:row.active};}
async function authenticate(req,res,next){try{if(req.get('X-Betipul-Ingress')==='true'){const haUserId=req.get('X-Remote-User-Id')||'betipul-ingress-admin';const displayName=req.get('X-Remote-User-Display-Name')||'מנהל Home Assistant';const result=await pool.query("INSERT INTO users(display_name,role,ha_user_id) VALUES($1,'admin',$2) ON CONFLICT(ha_user_id) DO UPDATE SET display_name=EXCLUDED.display_name,last_login_at=NOW() RETURNING *",[displayName,haUserId]);req.user=publicUser(result.rows[0]);if(req.path==='/api/bootstrap')console.log('BETIPUL ingress authentication ready');return next();}const token=cookieValue(req,'betipul_session')||req.get('Authorization')?.replace(/^Bearer\s+/i,'');if(!token){if(req.path==='/api/bootstrap')console.warn('BETIPUL bootstrap received without ingress marker');return res.status(401).json({error:'נדרשת התחברות'});}const payload=jwt.verify(token,jwtSecret);const result=await pool.query('SELECT * FROM users WHERE id=$1 AND active=TRUE',[payload.sub]);if(!result.rowCount)return res.status(401).json({error:'המשתמש אינו זמין'});req.user=publicUser(result.rows[0]);next();}catch(error){const fingerprint=safeErrorFingerprint(error);console.error(`[${fingerprint}] authentication failed`,{ingress:req.get('X-Betipul-Ingress')==='true',code:error.code||error.name});return res.status(401).json({error:'ההתחברות פגה',reference:fingerprint});}}
function requireRoles(...roles){return(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'אין הרשאה לפעולה'});}
async function audit(req,action,entityType,entityId,details={}){const ipHash=createHash('sha256').update(String(req.ip||'')).digest('hex').slice(0,20);await pool.query('INSERT INTO audit_log(user_id,action,entity_type,entity_id,details,ip_hash) VALUES($1,$2,$3,$4,$5,$6)',[req.user?.id||null,action,entityType,entityId,details,ipHash]);}
function required(value,label){const cleaned=String(value||'').trim();if(!cleaned)throw Object.assign(new Error(`${label} הוא שדה חובה`),{statusCode:400});return cleaned;}
function enc(value,context){return fields.encrypt(value,context);}
function dec(value,context){return fields.decrypt(value,context);}
function personFromRow(row){return {id:row.id,displayName:dec(row.display_name_enc,'person.name'),idNumber:dec(row.id_number_enc,'person.id'),birthDate:dec(row.birth_date_enc,'person.birth'),phone:dec(row.phone_enc,'person.phone'),email:dec(row.email_enc,'person.email'),address:dec(row.address_enc,'person.address'),emergencyContact:dec(row.emergency_contact_enc,'person.emergency'),status:row.status,createdAt:row.created_at};}
function caseFromRow(row){return {id:row.id,code:row.code,type:row.case_type,title:dec(row.title_enc,'case.title'),status:row.status,leadTherapistId:row.lead_therapist_id,leadTherapist:row.lead_therapist,organizationId:row.organization_id,organization:row.organization,payerType:row.payer_type,defaultFee:Number(row.default_fee),sessionMinutes:row.session_minutes,openedAt:row.opened_at,closedAt:row.closed_at,referral:dec(row.referral_enc,'case.referral'),clinicalSummary:dec(row.clinical_summary_enc,'case.summary'),participantCount:Number(row.participant_count||0),nextAppointment:row.next_appointment};}
function canSeeAllAdministrative(user){return ['admin','office','finance'].includes(user.role);}
function caseScope(user,alias='c'){if(canSeeAllAdministrative(user))return {sql:'TRUE',params:[]};return {sql:`(${alias}.lead_therapist_id=$1 OR EXISTS (SELECT 1 FROM case_access ca WHERE ca.case_id=${alias}.id AND ca.user_id=$1))`,params:[user.id]};}
async function assertClinicalAccess(req,caseId){if(req.user.role==='admin')return; if(!['therapist','supervisor'].includes(req.user.role))throw Object.assign(new Error('אין הרשאה למידע קליני'),{statusCode:403});const found=await pool.query('SELECT 1 FROM care_cases c WHERE c.id=$1 AND (c.lead_therapist_id=$2 OR EXISTS(SELECT 1 FROM case_access ca WHERE ca.case_id=c.id AND ca.user_id=$2 AND ca.access_level IN(\'clinical\',\'supervision\'))) ',[caseId,req.user.id]);if(!found.rowCount)throw Object.assign(new Error('אין הרשאה לתיק זה'),{statusCode:403});}

const loginAttempts=new Map();
app.get('/api/health',asyncRoute(async(_req,res)=>{await pool.query('SELECT 1');res.json({status:'ok',database:'ok',version:APP_VERSION,encryption:'aes-256-gcm',standaloneLoginReady});}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{if(!standaloneLoginReady)return res.status(503).json({error:'הגישה העצמאית חסומה עד להגדרת סיסמה ייחודית בת 12 תווים לפחות בהגדרות היישום'});const key=req.ip;const attempt=loginAttempts.get(key)||{count:0,until:0};if(attempt.until>Date.now())return res.status(429).json({error:'יותר מדי ניסיונות. נסו שוב מאוחר יותר'});const username=String(req.body?.username||'').trim();const password=String(req.body?.password||'');const result=await pool.query('SELECT * FROM users WHERE username=$1 AND active=TRUE',[username]);if(!result.rowCount||!result.rows[0].password_hash||!await bcrypt.compare(password,result.rows[0].password_hash)){attempt.count++;if(attempt.count>=5){attempt.until=Date.now()+15*60*1000;attempt.count=0;}loginAttempts.set(key,attempt);return res.status(401).json({error:'שם המשתמש או הסיסמה שגויים'});}loginAttempts.delete(key);const user=publicUser(result.rows[0]);await pool.query('UPDATE users SET last_login_at=NOW() WHERE id=$1',[user.id]);const token=jwt.sign({sub:user.id,role:user.role},jwtSecret,{expiresIn:'8h'});res.cookie('betipul_session',token,{httpOnly:true,sameSite:'strict',secure:req.get('X-Forwarded-Proto')==='https',maxAge:8*60*60*1000,path:'/'});res.json({user});}));
app.post('/api/auth/logout',(_req,res)=>{res.clearCookie('betipul_session',{path:'/'});res.status(204).end();});

app.get('/api/bootstrap',authenticate,asyncRoute(async(req,res)=>{const clinic=await pool.query("SELECT value FROM app_settings WHERE key='clinic'");res.json({user:req.user,clinic:clinic.rows[0]?.value||{},version:APP_VERSION});}));
app.get('/api/dashboard',authenticate,asyncRoute(async(req,res)=>{const scope=caseScope(req.user);const [stats,today,tasks]=await Promise.all([pool.query(`SELECT COUNT(*) FILTER(WHERE c.status='active')::int active_cases,COALESCE(SUM(a.fee) FILTER(WHERE a.payment_status='unpaid'),0) unpaid FROM care_cases c LEFT JOIN appointments a ON a.case_id=c.id WHERE ${scope.sql}`,scope.params),pool.query(`SELECT a.*,c.code,c.title_enc,u.display_name therapist FROM appointments a JOIN care_cases c ON c.id=a.case_id LEFT JOIN users u ON u.id=a.therapist_id WHERE ${scope.sql} AND a.starts_at>=date_trunc('day',NOW()) AND a.starts_at<date_trunc('day',NOW())+interval '1 day' ORDER BY a.starts_at`,scope.params),pool.query("SELECT * FROM tasks WHERE assigned_to=$1 AND status='open' ORDER BY due_at NULLS LAST LIMIT 8",[req.user.id])]);res.json({stats:{activeCases:stats.rows[0].active_cases,unpaid:Number(stats.rows[0].unpaid),today:today.rowCount,openTasks:tasks.rowCount},appointments:today.rows.map(r=>({...r,title:dec(r.title_enc,'case.title'),fee:Number(r.fee),title_enc:undefined})),tasks:tasks.rows});}));

app.get('/api/people',authenticate,asyncRoute(async(req,res)=>{const result=await pool.query('SELECT * FROM people WHERE status<>\'archived\' ORDER BY created_at DESC');res.json({people:result.rows.map(personFromRow)});}));
app.post('/api/people',authenticate,requireRoles('admin','therapist','office'),asyncRoute(async(req,res)=>{const name=required(req.body.displayName,'שם');const result=await pool.query(`INSERT INTO people(display_name_enc,id_number_enc,birth_date_enc,phone_enc,email_enc,address_enc,emergency_contact_enc,contact_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[enc(name,'person.name'),enc(req.body.idNumber,'person.id'),enc(req.body.birthDate,'person.birth'),enc(req.body.phone,'person.phone'),enc(req.body.email,'person.email'),enc(req.body.address,'person.address'),enc(req.body.emergencyContact,'person.emergency'),fields.lookupHash(req.body.phone||req.body.email||name),req.user.id]);await audit(req,'person_created','person',result.rows[0].id);res.status(201).json({person:personFromRow(result.rows[0])});}));
app.patch('/api/people/:id',authenticate,requireRoles('admin','therapist','office'),asyncRoute(async(req,res)=>{const current=await pool.query('SELECT * FROM people WHERE id=$1',[req.params.id]);if(!current.rowCount)return res.status(404).json({error:'האדם לא נמצא'});const old=personFromRow(current.rows[0]);const data={...old,...req.body};const result=await pool.query(`UPDATE people SET display_name_enc=$1,id_number_enc=$2,birth_date_enc=$3,phone_enc=$4,email_enc=$5,address_enc=$6,emergency_contact_enc=$7,status=$8,updated_at=NOW() WHERE id=$9 RETURNING *`,[enc(required(data.displayName,'שם'),'person.name'),enc(data.idNumber,'person.id'),enc(data.birthDate,'person.birth'),enc(data.phone,'person.phone'),enc(data.email,'person.email'),enc(data.address,'person.address'),enc(data.emergencyContact,'person.emergency'),data.status,req.params.id]);await audit(req,'person_updated','person',req.params.id);res.json({person:personFromRow(result.rows[0])});}));

function organizationFromRow(row){return {...row,contact_name:dec(row.contact_name_enc,'organization.contact'),contact_email:dec(row.contact_email_enc,'organization.email'),contact_phone:dec(row.contact_phone_enc,'organization.phone'),contact_name_enc:undefined,contact_email_enc:undefined,contact_phone_enc:undefined};}
app.get('/api/organizations',authenticate,asyncRoute(async(_req,res)=>{res.json({organizations:(await pool.query('SELECT * FROM organizations WHERE active=TRUE ORDER BY name')).rows.map(organizationFromRow)});}));
app.post('/api/organizations',authenticate,requireRoles('admin','office','finance'),asyncRoute(async(req,res)=>{const result=await pool.query('INSERT INTO organizations(name,kind,contact_name_enc,contact_email_enc,contact_phone_enc,billing_terms) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[required(req.body.name,'שם גוף'),req.body.kind||'other',enc(req.body.contactName,'organization.contact'),enc(req.body.contactEmail,'organization.email'),enc(req.body.contactPhone,'organization.phone'),req.body.billingTerms||'']);await audit(req,'organization_created','organization',result.rows[0].id);res.status(201).json({organization:organizationFromRow(result.rows[0])});}));

const caseSelect=`SELECT c.*,u.display_name lead_therapist,o.name organization,(SELECT COUNT(*) FROM case_participants cp WHERE cp.case_id=c.id) participant_count,(SELECT MIN(a.starts_at) FROM appointments a WHERE a.case_id=c.id AND a.starts_at>NOW() AND a.status IN('scheduled','confirmed')) next_appointment FROM care_cases c LEFT JOIN users u ON u.id=c.lead_therapist_id LEFT JOIN organizations o ON o.id=c.organization_id`;
app.get('/api/cases',authenticate,asyncRoute(async(req,res)=>{const scope=caseScope(req.user);const result=await pool.query(`${caseSelect} WHERE ${scope.sql} AND c.status<>'archived' ORDER BY c.updated_at DESC`,scope.params);res.json({cases:result.rows.map(caseFromRow)});}));
app.post('/api/cases',authenticate,requireRoles('admin','therapist','office'),asyncRoute(async(req,res)=>{const type=['individual','couple','family','group'].includes(req.body.type)?req.body.type:'individual';const title=required(req.body.title,'שם התיק');const next=await pool.query("SELECT 'BT-'||to_char(CURRENT_DATE,'YY')||'-'||lpad((COALESCE(MAX(NULLIF(regexp_replace(code,'\\D','','g'),'' )::int),0)+1)::text,4,'0') code FROM care_cases");const lead=req.body.leadTherapistId||(req.user.role==='therapist'?req.user.id:null);if(!lead&&req.user.role!=='admin')throw Object.assign(new Error('יש לבחור מטפל/ת מוביל/ה לתיק'),{statusCode:400});const result=await pool.query(`INSERT INTO care_cases(code,case_type,title_enc,status,lead_therapist_id,organization_id,payer_type,default_fee,session_minutes,referral_enc,clinical_summary_enc,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[next.rows[0].code,type,enc(title,'case.title'),req.body.status||'intake',lead,req.body.organizationId||null,req.body.payerType||'private',Number(req.body.defaultFee)||0,Number(req.body.sessionMinutes)||50,enc(req.body.referral,'case.referral'),enc(req.body.clinicalSummary,'case.summary'),req.user.id]);if(lead)await pool.query("INSERT INTO case_access(case_id,user_id,access_level,granted_by) VALUES($1,$2,'clinical',$3) ON CONFLICT DO NOTHING",[result.rows[0].id,lead,req.user.id]);for(const personId of req.body.participantIds||[])await pool.query('INSERT INTO case_participants(case_id,person_id,is_primary) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[result.rows[0].id,personId,personId===req.body.participantIds[0]]);await audit(req,'case_created','case',result.rows[0].id,{type});res.status(201).json({case:caseFromRow({...result.rows[0],participant_count:(req.body.participantIds||[]).length})});}));
app.get('/api/cases/:id',authenticate,asyncRoute(async(req,res)=>{const scope=caseScope(req.user);const params=[...scope.params,req.params.id];const result=await pool.query(`${caseSelect} WHERE ${scope.sql} AND c.id=$${params.length}`,params);if(!result.rowCount)return res.status(404).json({error:'התיק לא נמצא'});const participants=await pool.query('SELECT cp.*,p.* FROM case_participants cp JOIN people p ON p.id=cp.person_id WHERE cp.case_id=$1',[req.params.id]);res.json({case:caseFromRow(result.rows[0]),participants:participants.rows.map(r=>({...personFromRow(r),role:r.participant_role,isPrimary:r.is_primary,billingResponsible:r.billing_responsible,consentStatus:r.consent_status}))});}));
app.patch('/api/cases/:id',authenticate,requireRoles('admin','therapist','office'),asyncRoute(async(req,res)=>{const scope=caseScope(req.user);const params=[...scope.params,req.params.id];const found=await pool.query(`${caseSelect} WHERE ${scope.sql} AND c.id=$${params.length}`,params);if(!found.rowCount)return res.status(404).json({error:'התיק לא נמצא'});const old=caseFromRow(found.rows[0]);const d={...old,...req.body};const result=await pool.query(`UPDATE care_cases SET case_type=$1,title_enc=$2,status=$3,organization_id=$4,payer_type=$5,default_fee=$6,session_minutes=$7,referral_enc=$8,clinical_summary_enc=$9,updated_at=NOW() WHERE id=$10 RETURNING *`,[d.type,enc(required(d.title,'שם התיק'),'case.title'),d.status,d.organizationId||null,d.payerType,Number(d.defaultFee)||0,Number(d.sessionMinutes)||50,enc(d.referral,'case.referral'),enc(d.clinicalSummary,'case.summary'),req.params.id]);await audit(req,'case_updated','case',req.params.id,{status:d.status});res.json({case:caseFromRow(result.rows[0])});}));
app.post('/api/cases/:id/participants',authenticate,requireRoles('admin','therapist','office'),asyncRoute(async(req,res)=>{await pool.query('INSERT INTO case_participants(case_id,person_id,participant_role,is_primary,billing_responsible,consent_status) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(case_id,person_id) DO UPDATE SET participant_role=EXCLUDED.participant_role,is_primary=EXCLUDED.is_primary,billing_responsible=EXCLUDED.billing_responsible,consent_status=EXCLUDED.consent_status',[req.params.id,req.body.personId,req.body.role||'client',Boolean(req.body.isPrimary),Boolean(req.body.billingResponsible),req.body.consentStatus||'pending']);await audit(req,'participant_linked','case',req.params.id);res.status(204).end();}));

app.get('/api/appointments',authenticate,asyncRoute(async(req,res)=>{const scope=caseScope(req.user);const from=req.query.from||new Date(Date.now()-7*86400000).toISOString();const to=req.query.to||new Date(Date.now()+45*86400000).toISOString();const params=[...scope.params,from,to];const result=await pool.query(`SELECT a.*,c.code,c.title_enc,u.display_name therapist FROM appointments a JOIN care_cases c ON c.id=a.case_id LEFT JOIN users u ON u.id=a.therapist_id WHERE ${scope.sql} AND a.starts_at>=$${params.length-1} AND a.starts_at<$${params.length} ORDER BY a.starts_at`,params);res.json({appointments:result.rows.map(r=>({...r,title:dec(r.title_enc,'case.title'),location:dec(r.location_enc,'appointment.location'),meetingUrl:dec(r.meeting_url_enc,'appointment.url'),fee:Number(r.fee),title_enc:undefined,location_enc:undefined,meeting_url_enc:undefined}))});}));
app.post('/api/appointments',authenticate,requireRoles('admin','therapist','office'),asyncRoute(async(req,res)=>{const caseId=required(req.body.caseId,'תיק');const care=await pool.query('SELECT default_fee,lead_therapist_id FROM care_cases WHERE id=$1',[caseId]);if(!care.rowCount)return res.status(404).json({error:'התיק לא נמצא'});const therapistId=req.body.therapistId||(req.user.role==='therapist'?req.user.id:care.rows[0].lead_therapist_id);if(!therapistId)throw Object.assign(new Error('לא הוגדר/ה מטפל/ת למפגש'),{statusCode:400});const startsAt=new Date(req.body.startsAt);const endsAt=new Date(req.body.endsAt);if(!(startsAt<endsAt))throw Object.assign(new Error('שעות המפגש אינן תקינות'),{statusCode:400});const conflict=await pool.query("SELECT 1 FROM appointments WHERE therapist_id=$1 AND status IN('scheduled','confirmed') AND starts_at<$3 AND ends_at>$2",[therapistId,startsAt,endsAt]);if(conflict.rowCount&&!req.body.overrideConflict)return res.status(409).json({error:'קיימת פגישה חופפת ביומן',code:'APPOINTMENT_CONFLICT'});const result=await pool.query(`INSERT INTO appointments(case_id,therapist_id,starts_at,ends_at,location_type,location_enc,meeting_url_enc,status,fee,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[caseId,therapistId,startsAt,endsAt,req.body.locationType||'clinic',enc(req.body.location,'appointment.location'),enc(req.body.meetingUrl,'appointment.url'),req.body.status||'scheduled',req.body.fee??care.rows[0].default_fee,req.user.id]);await audit(req,'appointment_created','appointment',result.rows[0].id,{caseId});res.status(201).json({appointment:result.rows[0]});}));
app.patch('/api/appointments/:id',authenticate,requireRoles('admin','therapist','office','finance'),asyncRoute(async(req,res)=>{const current=await pool.query('SELECT * FROM appointments WHERE id=$1',[req.params.id]);if(!current.rowCount)return res.status(404).json({error:'המפגש לא נמצא'});const d={...current.rows[0],...req.body};const result=await pool.query('UPDATE appointments SET status=$1,payment_status=$2,attendance=$3,fee=$4,updated_at=NOW() WHERE id=$5 RETURNING *',[d.status,d.paymentStatus||d.payment_status,d.attendance,Number(d.fee)||0,req.params.id]);await audit(req,'appointment_updated','appointment',req.params.id,{status:d.status,paymentStatus:d.paymentStatus});res.json({appointment:result.rows[0]});}));

app.get('/api/notes',authenticate,requireRoles('admin','therapist','supervisor'),asyncRoute(async(req,res)=>{const scope=caseScope(req.user,'c');const result=await pool.query(`SELECT n.*,c.code,c.title_enc,u.display_name author FROM clinical_notes n JOIN care_cases c ON c.id=n.case_id JOIN users u ON u.id=n.author_id WHERE ${scope.sql} ORDER BY n.created_at DESC LIMIT 100`,scope.params);res.json({notes:result.rows.map(r=>({id:r.id,caseId:r.case_id,appointmentId:r.appointment_id,caseCode:r.code,caseTitle:dec(r.title_enc,'case.title'),author:r.author,template:r.template,content:dec(r.content_enc,'note.content'),risk:dec(r.risk_enc,'note.risk'),state:r.state,version:r.version,signedAt:r.signed_at,createdAt:r.created_at,updatedAt:r.updated_at}))});}));
app.post('/api/notes',authenticate,requireRoles('admin','therapist'),asyncRoute(async(req,res)=>{await assertClinicalAccess(req,req.body.caseId);const content=required(req.body.content,'תוכן הרשומה');const result=await pool.query(`INSERT INTO clinical_notes(case_id,appointment_id,author_id,template,content_enc,risk_enc) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.body.caseId,req.body.appointmentId||null,req.user.id,req.body.template||'free',enc(content,'note.content'),enc(req.body.risk,'note.risk')]);await audit(req,'note_created','clinical_note',result.rows[0].id,{caseId:req.body.caseId});res.status(201).json({note:{id:result.rows[0].id,state:'draft'}});}));
app.patch('/api/notes/:id',authenticate,requireRoles('admin','therapist'),asyncRoute(async(req,res)=>{const current=await pool.query('SELECT * FROM clinical_notes WHERE id=$1',[req.params.id]);if(!current.rowCount)return res.status(404).json({error:'הרשומה לא נמצאה'});await assertClinicalAccess(req,current.rows[0].case_id);if(current.rows[0].state==='signed')return res.status(409).json({error:'רשומה חתומה אינה ניתנת לעריכה; יש ליצור תיקון'});const result=await pool.query('UPDATE clinical_notes SET content_enc=$1,risk_enc=$2,template=$3,version=version+1,updated_at=NOW() WHERE id=$4 RETURNING *',[enc(req.body.content??dec(current.rows[0].content_enc,'note.content'),'note.content'),enc(req.body.risk??dec(current.rows[0].risk_enc,'note.risk'),'note.risk'),req.body.template||current.rows[0].template,req.params.id]);await audit(req,'note_updated','clinical_note',req.params.id,{version:result.rows[0].version});res.json({note:{id:result.rows[0].id,version:result.rows[0].version}});}));
app.post('/api/notes/:id/sign',authenticate,requireRoles('admin','therapist'),asyncRoute(async(req,res)=>{const current=await pool.query('SELECT * FROM clinical_notes WHERE id=$1',[req.params.id]);if(!current.rowCount)return res.status(404).json({error:'הרשומה לא נמצאה'});await assertClinicalAccess(req,current.rows[0].case_id);const result=await pool.query("UPDATE clinical_notes SET state='signed',signed_at=NOW(),signed_by=$1,updated_at=NOW() WHERE id=$2 AND state='draft' RETURNING *",[req.user.id,req.params.id]);if(!result.rowCount)return res.status(409).json({error:'הרשומה כבר חתומה'});await audit(req,'note_signed','clinical_note',req.params.id);res.json({note:{id:req.params.id,state:'signed',signedAt:result.rows[0].signed_at}});}));

app.get('/api/finance',authenticate,requireRoles('admin','finance','office','therapist'),asyncRoute(async(req,res)=>{const scope=caseScope(req.user);const [summary,rows]=await Promise.all([pool.query(`SELECT COALESCE(SUM(a.fee) FILTER(WHERE a.status='completed'),0) billed,COALESCE(SUM(a.fee) FILTER(WHERE a.payment_status='paid'),0) paid,COALESCE(SUM(a.fee) FILTER(WHERE a.payment_status='unpaid' AND a.status='completed'),0) outstanding FROM appointments a JOIN care_cases c ON c.id=a.case_id WHERE ${scope.sql}`,scope.params),pool.query(`SELECT a.id,a.starts_at,a.fee,a.payment_status,c.code,c.title_enc FROM appointments a JOIN care_cases c ON c.id=a.case_id WHERE ${scope.sql} AND a.status='completed' ORDER BY a.starts_at DESC LIMIT 100`,scope.params)]);res.json({summary:Object.fromEntries(Object.entries(summary.rows[0]).map(([k,v])=>[k,Number(v)])),rows:rows.rows.map(r=>({...r,title:dec(r.title_enc,'case.title'),fee:Number(r.fee),title_enc:undefined}))});}));

app.get('/api/tasks',authenticate,asyncRoute(async(req,res)=>res.json({tasks:(await pool.query('SELECT * FROM tasks WHERE assigned_to=$1 ORDER BY status,due_at NULLS LAST',[req.user.id])).rows})));
app.post('/api/tasks',authenticate,asyncRoute(async(req,res)=>{const result=await pool.query('INSERT INTO tasks(case_id,assigned_to,title,due_at) VALUES($1,$2,$3,$4) RETURNING *',[req.body.caseId||null,req.body.assignedTo||req.user.id,required(req.body.title,'משימה'),req.body.dueAt||null]);await audit(req,'task_created','task',result.rows[0].id);res.status(201).json({task:result.rows[0]});}));

app.get('/api/users',authenticate,requireRoles('admin'),asyncRoute(async(_req,res)=>res.json({users:(await pool.query('SELECT id,username,display_name,role,active,last_login_at FROM users ORDER BY display_name')).rows})));
app.get('/api/audit',authenticate,requireRoles('admin'),asyncRoute(async(_req,res)=>res.json({entries:(await pool.query('SELECT a.*,u.display_name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 200')).rows})));
app.patch('/api/settings/clinic',authenticate,requireRoles('admin'),asyncRoute(async(req,res)=>{const value={name:required(req.body.name,'שם הקליניקה'),timezone:req.body.timezone||'Asia/Jerusalem',currency:req.body.currency||'ILS'};await pool.query("INSERT INTO app_settings(key,value,updated_by) VALUES('clinic',$1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_by=EXCLUDED.updated_by,updated_at=NOW()",[value,req.user.id]);await audit(req,'clinic_settings_updated','system','clinic');res.json({clinic:value});}));
app.use('/api',await createBackupRouter({pool,authenticate,requireRoles,audit,dataDir:DATA_DIR,passphrase:options.backup_passphrase,appVersion:APP_VERSION}));

app.use('/api',(_req,res)=>res.status(404).json({error:'הנתיב לא נמצא'}));
app.use((error,_req,res,_next)=>{const fingerprint=safeErrorFingerprint(error);console.error(`[${fingerprint}]`,error);if(error.statusCode)return res.status(error.statusCode).json({error:error.message});if(error.code==='23505')return res.status(409).json({error:'כבר קיימת רשומה עם פרטים אלה'});if(error.code==='23503')return res.status(409).json({error:'הרשומה נמצאת בשימוש ולא ניתן להסירה'});res.status(500).json({error:'אירעה שגיאה פנימית',reference:fingerprint});});
const server=app.listen(PORT,'127.0.0.1',()=>console.log(`BETIPUL API ${APP_VERSION} listening on ${PORT}`));
async function shutdown(){server.close();await pool.end();process.exit(0);}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
